### ISSUE TITLE
pip install masspy not working

### ISSUE THREAD

**Issue by ilknuricke** [SBRG/MASSpy#154]
......
Collecting swiglpk
  Using cached swiglpk-4.65.1.tar.gz (30 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Ilknur\anaconda3\envs\masspy\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ilknur\\AppData\\Local\\Temp\\pip-install-jkgdvhfk\\swiglpk_2f4580227db041b9b88e4cd94c33661c\\setup.py'"'"'; __file__='"'"'C:\\Users\\Ilknur\\AppData\\Local\\Temp\\pip-install-jkgdvhfk\\swiglpk_2f4580227db041b9b88e4cd94c33661c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Ilknur\AppData\Local\Temp\pip-pip-egg-info-zer12uhm'
         cwd: C:\Users\Ilknur\AppData\Local\Temp\pip-install-jkgdvhfk\swiglpk_2f4580227db041b9b88e4cd94c33661c\
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ilknur\AppData\Local\Temp\pip-install-jkgdvhfk\swiglpk_2f4580227db041b9b88e4cd94c33661c\setup.py", line 53, in <module>
        copy_glpk_header()
      File "C:\Users\Ilknur\AppData\Local\Temp\pip-install-jkgdvhfk\swiglpk_2f4580227db041b9b88e4cd94c33661c\setup.py", line 31, in copy_glpk_header
        glpsol_path = os.path.dirname(subprocess.check_output(['which', 'glpsol']))
      File "C:\Users\Ilknur\anaconda3\envs\masspy\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\Ilknur\anaconda3\envs\masspy\lib\subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\Ilknur\anaconda3\envs\masspy\lib\subprocess.py", line 947, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\Ilknur\anaconda3\envs\masspy\lib\subprocess.py", line 1416, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    Trying to determine glpk.h location
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ilknuricke** [comment]
I was able to install the package from the tar.gz by manually installing glpk, swig and downgrading some dependencies. However, when I run the example code from the textbook, my simulation plots don't look like those on the example results from the website.
